### ISSUE TITLE
Weird issue with textfield

### ISSUE THREAD

**Issue by egeland** [genadis/aurelia-mdl#7] opened 2016-02-11 04:15 UTC
On my page, I have between 1 and _n_ textfields (I use a `repeat.for`), and I'm getting this odd behaviour:

![image](https://cloud.githubusercontent.com/assets/1281379/12969183/39fa7498-d0c0-11e5-8904-615301a3a352.png)

As you can see, the `<label>` floats ok for the bottom textfield, but is not floating in the first.
The only difference in where the two are getting their content is that the top one gets it straight from an object property (`value.bind="taskDetails.server"`) and the lower one gets it from an array that's repeated over. I'll put the code below for reference.

**Note**: If I edit the text in the top textfield, the label then floats properly, it's just when the data gets placed there by the `value.bind` that it's behaving weirdly. :confused: 

Any idea what I'm doing wrong here, to get this odd behaviour? Have you seen anything like this?

Cheers! :smile: 

Code:

```
<template>

  <div mdl="grid">

    <div class="mdl-cell mdl-cell--12-col-desktop">
      <div mdl="grid" class="mdl-grid--no-spacing">

        <div class="mdl-cell mdl-cell--6-col-desktop mdl-cell--6-col-tablet">
          <div mdl="textfield" class="mdl-textfield--floating-label">
            <input id="server" class="mdl-textfield__input" type="text" value.bind="taskDetails.server" disabled.bind="!edit">
            <label for="server" class="mdl-textfield__label">Server to target</label>
          </div>
        </div>

      </div>
    </div>

    <div class="mdl-cell mdl-cell--12-col-desktop" repeat.for="url of taskDetails.urls">

      <div mdl="grid" class="mdl-grid--no-spacing">

        <div class="mdl-cell mdl-cell--6-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
          <div mdl="textfield" class="mdl-textfield--floating-label">
            <input id="edit_${$index}" class="mdl-textfield__input" type="text" value.bind="url" disabled.bind="!edit">
            <label for="edit_${$index}" class="mdl-textfield__label" >URL</label>
          </div>
        </div>

        <div class="mdl-cell mdl-cell--middle mdl-cell--1-col">
          <div if.bind="edit">
            <button
            id="delbutton-${$index}"
            mdl="button"
            class="mdl-button--icon mdl-button--accent mdl-js-ripple-effect"
            click.trigger="del($index)">
            <i class="mdi mdi-delete"></i>
          </button>
          <label mdl="tooltip" class="mdl-tooltip--top" for="delbutton-${$index}">
            Remove URL
          </label>
        </div>
      </div>

      </div>

    </div>
  </div>

</template>
```

**Comment by genadis** [comment] 2016-02-15 11:32
I think it is expected behavior not related to the plugin. 

the label should float when the text field has focus.
Not sure how more than one text field can have focus at the same time.
Check out the MDL [textfield component section](http://www.getmdl.io/components/index.html#textfields-section), there are 2 floating labels texfields side by side, if one get's focus the second one losses it.

It is intended for dynamic label floating on focus, not as in your use case where you just want to show labels above the texfield. You should just add your own labels and style it.

**Comment by Thanood** [comment] 2016-02-15 11:41
From what I've experienced, MDL doesn't update the text field when the `input` is assigned a value by using code.

You could work around that by calling `upgradedElement.MaterialTextfield.checkDirty()`.

Here's a plunk to demonstrate this:
http://plnkr.co/edit/gxvfUuFqGJtuGIRhHQII?p=preview

**Comment by egeland** [comment] 2016-02-15 12:19
I'll take a look at it, thanks! Will update with how I go.

**Comment by genadis** [comment] 2016-02-15 13:08
@Thanood  that does the trick... tahnks!
I've added another text field to demonstrate:
http://plnkr.co/edit/5pQhsgUGJ78GrpKbrlQ4?p=preview

But again I think that it falls to the custom element category because it is a custom behavior to the textfield.

**Comment by Thanood** [comment] 2016-02-15 14:27
Right, you already expose the upgraded element in your event publisher, so "consumers" can use that to work around such issues. :smile:

**Comment by genadis** [comment] 2016-02-15 15:15
It's not ideal to say the least...
But the right way to do it would be to implement custom elements for the different components.
It would make the plugin more like a framework, unfortunately I don't have the capacity to implement and maintain it.

I will create a wiki page with examples of custom elements based on the opened issues, hopefully it would help.

**Comment by Thanood** [comment] 2016-02-15 15:41
Are you sure? Most of the work would probably be writing documentation. :smile: 
You could even use something like this as a foundation: https://github.com/Thanood/aurelia-mdl-skeleton-navigation/tree/master/src/aurelia-mdl

But your decision, of course. :smile: 

As for this plugin. I think that you are right that such issues are out of the scope of this attribute. Some wiki pages explaining such issues would be great!

I love your encapsulated mdl version, btw.

**Comment by genadis** [comment] 2016-02-15 18:58
thank you for the feedback and the link :)

In any case, if I'll decide to do something like this it would be separate plugin aurelia-mdl-components maybe, i already have some from the project I'm working on.

I'm closing the issue for now...

**Closed as completed by genadis** 2016-02-15 18:58 UTC

**Comment by egeland** [comment] 2016-02-19 06:18
For future reference, I added a util function to my app:

```
// The floating labels can get stuck as placeholders when loading data
// This fixes that by forcing a dirty check.
export function fixTextinputLabels() {
    setTimeout(_fixTextinputLabels, 0);
}
function _fixTextinputLabels() {
    let elems = document.getElementsByClassName('mdl-textfield--floating-label');
    for (let i = 0; i < elems.length; i++) {
        elems[i].MaterialTextfield.checkDirty();
    }
}
```

I just import that in the VM I have textfields, and call it after loading any data. :smile: 

```
async attached() {
    this.taskDetails = await this.api.fetchTaskDetail(this.listId);
    fixTextinputLabels();
}
```
